#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Passave.Resource", IsApplication=true)]

namespace Passave
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_right = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_up = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f070000
			public const int theme_devicedefault_background = 2131165184;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ButtonCreateStyle = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ButtonSignInStyle = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int DescriptionEditStyle = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int edit_text_style = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_action_new = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_action_search = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_help_outline_white_24dp = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_settings_white_24dp = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Icon = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ProgressBarStyle = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int search = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int xs = 2130837515;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f09002f
			public const int About = 2131296303;
			
			// aapt resource value: 0x7f090002
			public const int AddItem = 2131296258;
			
			// aapt resource value: 0x7f09002d
			public const int ChangeName = 2131296301;
			
			// aapt resource value: 0x7f09002e
			public const int ChangePassword = 2131296302;
			
			// aapt resource value: 0x7f090031
			public const int LogOut = 2131296305;
			
			// aapt resource value: 0x7f090030
			public const int Support = 2131296304;
			
			// aapt resource value: 0x7f09002b
			public const int add = 2131296299;
			
			// aapt resource value: 0x7f09000a
			public const int btnAdd = 2131296266;
			
			// aapt resource value: 0x7f09001d
			public const int btnBack = 2131296285;
			
			// aapt resource value: 0x7f090009
			public const int btnCancelAdd = 2131296265;
			
			// aapt resource value: 0x7f090012
			public const int btnCancelChPass = 2131296274;
			
			// aapt resource value: 0x7f090013
			public const int btnConfirmChPass = 2131296275;
			
			// aapt resource value: 0x7f090019
			public const int btnConfirmEdit = 2131296281;
			
			// aapt resource value: 0x7f090027
			public const int btnDialogReg = 2131296295;
			
			// aapt resource value: 0x7f09000e
			public const int btnEdit = 2131296270;
			
			// aapt resource value: 0x7f09000d
			public const int btnEditCancel = 2131296269;
			
			// aapt resource value: 0x7f090018
			public const int btnEditCanceled = 2131296280;
			
			// aapt resource value: 0x7f09001e
			public const int btnSubmitGo = 2131296286;
			
			// aapt resource value: 0x7f090028
			public const int btnSupBack = 2131296296;
			
			// aapt resource value: 0x7f090029
			public const int btnWrite = 2131296297;
			
			// aapt resource value: 0x7f090025
			public const int btn_SingIn = 2131296293;
			
			// aapt resource value: 0x7f090026
			public const int btn_SingUp = 2131296294;
			
			// aapt resource value: 0x7f090001
			public const int button1 = 2131296257;
			
			// aapt resource value: 0x7f090000
			public const int editAbout = 2131296256;
			
			// aapt resource value: 0x7f090011
			public const int editConfirmNewPassword = 2131296273;
			
			// aapt resource value: 0x7f090017
			public const int editDescription = 2131296279;
			
			// aapt resource value: 0x7f09000c
			public const int editEditName = 2131296268;
			
			// aapt resource value: 0x7f090015
			public const int editLogin = 2131296277;
			
			// aapt resource value: 0x7f090010
			public const int editNewPassword = 2131296272;
			
			// aapt resource value: 0x7f09000f
			public const int editOldPassword = 2131296271;
			
			// aapt resource value: 0x7f090016
			public const int editPassword = 2131296278;
			
			// aapt resource value: 0x7f090014
			public const int editUrl = 2131296276;
			
			// aapt resource value: 0x7f090021
			public const int etSearch = 2131296289;
			
			// aapt resource value: 0x7f090008
			public const int linearLayout1 = 2131296264;
			
			// aapt resource value: 0x7f090024
			public const int liner = 2131296292;
			
			// aapt resource value: 0x7f09001f
			public const int llContainer = 2131296287;
			
			// aapt resource value: 0x7f090020
			public const int myListView = 2131296288;
			
			// aapt resource value: 0x7f09002a
			public const int search = 2131296298;
			
			// aapt resource value: 0x7f09002c
			public const int settings = 2131296300;
			
			// aapt resource value: 0x7f09001b
			public const int textLogin = 2131296283;
			
			// aapt resource value: 0x7f090022
			public const int textNoItems = 2131296290;
			
			// aapt resource value: 0x7f09000b
			public const int textOldName = 2131296267;
			
			// aapt resource value: 0x7f09001c
			public const int textPassword = 2131296284;
			
			// aapt resource value: 0x7f09001a
			public const int textUrl = 2131296282;
			
			// aapt resource value: 0x7f090003
			public const int textView1 = 2131296259;
			
			// aapt resource value: 0x7f090007
			public const int txtDescription = 2131296263;
			
			// aapt resource value: 0x7f090005
			public const int txtLogin = 2131296261;
			
			// aapt resource value: 0x7f090023
			public const int txtName = 2131296291;
			
			// aapt resource value: 0x7f090006
			public const int txtPassword = 2131296262;
			
			// aapt resource value: 0x7f090004
			public const int txtUrl = 2131296260;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int About = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AddItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ChangeName = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ChangePassword = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int EditItem = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Information = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ListPage = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int listview_row = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Main = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Registration = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Support = 2130903050;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int actionbar = 2131230720;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060002
			public const int CustomActionBarTheme = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int MyActionBar = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int Theme_Custom = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int dialog_animation = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
